server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${APPLICATION_NAME}
  profiles.active: ${ACTIVE_PROFILE}
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
#    driver-class-name: org.postgresql.Driver

logging:
  level:
    io:
      cherrytechnologies:
        photoappapiusers:
          web:
            services:
              albums:
                AlbumsServiceClient: DEBUG


gateway:
  ip: ${GATEWAY_IP}

albums:
  url: albums-api

resilience4j:
  circuitbreaker:
    instances:
      albumServiceCircuitBreaker:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 4
        ring-buffer-size-in-half-open-state: 3
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
